Project setup
asanchezmpsl/psl-workshop-api-testing-js pull request #1
Opened 2017-09-23 00:20 UTC by asanchezmpsl

2017-09-24 16:24 UTC, germandavid85 requested changes
1. quita del commit todos los archivos que están dentro de `node_modules`
2. restaura el alrchivo `README.md` no hay que borrarlo

2017-09-24 16:25 UTC, aperdomob requested changes

2017-09-24 16:25 UTC, aperdomob commented on LICENSE
> +Copyright (c) 2017 <copyright holders>
cambiar <copyright holders> por su nombre

2017-09-24 16:25 UTC, aperdomob commented on README.md
> -# psl-workshop-api-testing-js
No eliminar este archivo

2017-09-25 22:38 UTC, aperdomob requested changes

2017-09-25 22:38 UTC, aperdomob commented on test/HelloWord.test.js
> +});
agrega una linea al final

2017-09-25 22:55 UTC, germandavid85 approved these changes

2017-09-25 22:56 UTC, aperdomob approved these changes

2017-09-25 23:02 UTC, merged